"""add gin index on show categories

Revision ID: 3d370fb0d3b0
Revises: 994dca82408c
Create Date: 2026-09-04 00:41:41.907377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d370fb0d3b0'
down_revision: Union[str, None] = '994dca82408c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_shows_categories', 'shows', ['categories'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shows_categories', table_name='shows', postgresql_using='gin')
    # ### end Alembic commands ###
