"""add catalog snapshot and rollback tracking to publish runs

Revision ID: 484141b08a4a
Revises: 8c22436f3966
Create Date: 2026-09-05 19:23:12.504223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '484141b08a4a'
down_revision: Union[str, None] = '8c22436f3966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publish_runs', sa.Column('catalog_snapshot', sa.JSON(), nullable=True))
    op.add_column('publish_runs', sa.Column('rolled_back_from_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'publish_runs', 'publish_runs', ['rolled_back_from_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'publish_runs', type_='foreignkey')
    op.drop_column('publish_runs', 'rolled_back_from_id')
    op.drop_column('publish_runs', 'catalog_snapshot')
    # ### end Alembic commands ###
