"""add detail column to publish_runs

Revision ID: 8c22436f3966
Revises: 3d370fb0d3b0
Create Date: 2026-09-04 16:05:27.018761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c22436f3966'
down_revision: Union[str, None] = '3d370fb0d3b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publish_runs', sa.Column('detail', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publish_runs', 'detail')
    # ### end Alembic commands ###
